apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: "ghcr.io/alexander-moser/website:main"
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
      automountServiceAccountToken: false
