apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: angular-app
              servicePort: 80
          - path: /test/(/|$)(.*)
            backend:
              serviceName: angular-app
              servicePort: 80
