apiVersion: extensions/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: angular-app
                port:
                  number: 80
          - path: /test/(/|$)(.*)
            backend:
              service:
                name: angular-app
                port:
                  number: 80
