apiVersion: v1
kind: Service
metadata:
  name: {{ include "website-helm.fullname" . }}
  labels:
    {{- include "website-helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
  selector:
    app: angular-app

