apiVersion: v1
kind: Service
metadata:
  name: {{ include "website-helm.fullname" . }}
  labels:
    {{- include "website-helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: angular-app

